spec:
  replicas: 1
  template:
    spec:
      containers:
        - 
#          resources:
#            requests:
#              cpu: "0.2"
#              memory: 256Mi
#            limits:
#              cpu: "1.0"
#              memory: 256Mi
          env:
          - name: MYSQL_SERVICE_NAME
            value: mysql
          - name: MYSQL_SERVICE_DATABASE
            value: sampledb
          - name: MYSQL_SERVICE_USERNAME
            valueFrom:
              secretKeyRef:
                key: database-user
                name: mysql
          - name: MYSQL_SERVICE_PASSWORD
            valueFrom:
              secretKeyRef:
                key: database-password
                name: mysql
