apiVersion: template.openshift.io/v1
kind: Template
labels:
    template: pipeline
metadata:
  annotations:
    description: RHTE CICD Deployment Pipeline
  name: pipeline
parameters:
- name: GIT_REPO
  value: https://github.com/rh-integration/IntegrationApp-Automation.git
  required: true
- name: GIT_BRANCH
  value: master
  required: true
- name: DEV_PROJECT 
  required: true
- name: TEST_PROJECT 
  required: true
- name: PROD_PROJECT 
  required: true
- name: MYSQL_USER 
  value: dbuser 
  required: true
- name: MYSQL_PWD
  value: password 
  required: true
- name: IMAGE_REGISTRY
  value: image-registry.openshift-image-registry.svc:5000
  required: true
- name: IMAGE_NAMESPACE 
  required: true
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: fuse-alert-service-pipeline
    labels:
      app: "cicd-pipeline"
  spec:
    output: null
    postCommit: null
    resources: null
    runPolicy: Serial
    source:
      type: None
    source:
      git:
        uri: ${GIT_REPO}
        ref: ${GIT_BRANCH}
    strategy:
      type: JenkinsPipeline
      jenkinsPipelineStrategy:
        jenkinsfilePath: fuse-alert-service/Jenkinsfile
        env:
        - name: GIT_BRANCH
          value: ${GIT_BRANCH}
        - name: GIT_REPO
          value: ${GIT_REPO}
        - name: DEV_PROJECT 
          value: ${DEV_PROJECT}
        - name: TEST_PROJECT 
          value: ${TEST_PROJECT}
        - name: PROD_PROJECT 
          value: ${PROD_PROJECT}
        - name: MYSQL_USER 
          value: ${MYSQL_USER}
        - name: MYSQL_PWD 
          value: ${MYSQL_PWD}
        - name: IMAGE_NAMESPACE 
          value: ${IMAGE_NAMESPACE}
        - name: IMAGE_REGISTRY 
          value: ${IMAGE_REGISTRY}
